// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../Panmenu/dist/component.js', ['DD.ui.Component'], ['DD.ui.EventType', 'DD.ui.renderer.Component', 'goog.ui.Component', 'goog.ui.registry'], false);
goog.addDependency('../../../../Panmenu/dist/componentrenderer.js', ['DD.ui.renderer.Component'], ['goog.array', 'goog.dom', 'goog.dom.classes', 'goog.style'], false);
goog.addDependency('../../../../Panmenu/dist/flickslider.js', ['DD.ui.flickSliders.FlickSlider'], ['DD.ui.List', 'DD.ui.flickSliders', 'DD.ui.flickSliders.Slide', 'DD.ui.flickSliders.renderer.FlickSlider', 'goog.ui.registry'], false);
goog.addDependency('../../../../Panmenu/dist/flicksliderrenderer.js', ['DD.ui.flickSliders.renderer.FlickSlider'], ['DD.ui.flickSliders.renderer', 'DD.ui.renderer.Component', 'goog.dom.classes'], false);
goog.addDependency('../../../../Panmenu/dist/flicksliders.js', ['DD.ui.flickSliders', 'DD.ui.flickSliders.renderer'], [], false);
goog.addDependency('../../../../Panmenu/dist/list.js', ['DD.ui.List'], ['DD.ui.Component', 'DD.ui.EventType', 'DD.ui.renderer.List', 'goog.array', 'goog.events.Event', 'goog.ui.registry'], false);
goog.addDependency('../../../../Panmenu/dist/listrenderer.js', ['DD.ui.renderer.List'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Panmenu/dist/panmenu.js', ['DD.ui.flickSliders.PanMenu'], ['DD.ui.flickSliders.FlickSlider', 'DD.ui.flickSliders.SlidePanMenu', 'DD.ui.flickSliders.renderer.PanMenu', 'goog.ui.registry'], false);
goog.addDependency('../../../../Panmenu/dist/panmenurenderer.js', ['DD.ui.flickSliders.renderer.PanMenu'], ['DD.ui.flickSliders.renderer', 'DD.ui.renderer.Component', 'goog.dom.classes', 'goog.fx.AnimationParallelQueue', 'goog.fx.dom.FadeInAndShow', 'goog.fx.dom.FadeOutAndHide', 'goog.style.transform'], false);
goog.addDependency('../../../../Panmenu/dist/panmenuslide.js', ['DD.ui.flickSliders.SlidePanMenu'], ['DD.ui.flickSliders.Slide', 'DD.ui.flickSliders.renderer.SlidePanMenu', 'goog.ui.registry'], false);
goog.addDependency('../../../../Panmenu/dist/panmenusliderenderer.js', ['DD.ui.flickSliders.renderer.SlidePanMenu'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Panmenu/dist/slide/renderer/slide.js', ['DD.ui.flickSliders.renderer.Slide'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Panmenu/dist/slide/slide.js', ['DD.ui.flickSliders.Slide'], ['DD.ui.Component', 'DD.ui.flickSliders.renderer.Slide', 'goog.ui.registry'], false);
goog.addDependency('../../../../Panmenu/dist/ui.js', ['DD.ui', 'DD.ui.EventType'], [], false);
